# Generated by Django 3.0.3 on 2020-09-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20200908_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
