# Generated by Django 3.0.3 on 2020-09-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20200908_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='picture_url',
        ),
        migrations.AlterField(
            model_name='goods',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='goods',
            name='trade_location',
            field=models.CharField(choices=[('学院路校区', '学院路校区'), ('沙河校区', '沙河校区')], default='学院路校区', max_length=32),
        ),
    ]
