# Generated by Django 3.0.3 on 2020-09-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20200911_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='buy_username',
            field=models.CharField(default='null', max_length=128),
        ),
    ]
